language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
install:
  - "pip install coveralls"
  - "pip install -e .[test]"
script:
  - nosetests --with-coverage --cover-package=multilog
after_success:
  - coveralls
sudo: false
